### ISSUE TITLE
error related to nltk

### ISSUE THREAD

**Issue by yashaswiniuma** [Zaab1t/bong#14]
i have installed python,nltk .did coding related stemming .
everything was fine.
but suddenly error came by showing that 'python' is not recognized as internal and external command
reinstalled python 2.7
now while importing nltk below error is showing
github
my project has come to end suddenly it happen
how to resolve this
thank you in advance
![github](https://user-images.githubusercontent.com/33446718/35716379-99436500-07fe-11e8-91cc-35a68f86d0ba.png)

**Comment by theelous3** [comment]
This seems unrelated to the project. An import error in PIL is not specific to bong. By the way, use python 3 :D
